---
title: "Dashboard"
format:
  dashboard: 
    orientation: columns
---


## Column {width="20%"}

### Row {height="30%"}

```{r, install_packages}
#| echo: false
#| include: false
library(tidyverse)
```

```{r, starwars}
x <- starwars
```
```{r, sendtoojs}
#| echo: false
#| include: false
ojs_define(service_name = x)
```

```{ojs}
viewof search = Inputs.search(service, {placeholder: "Type to find a service",
width: 150,
height: 10})

viewof items = Inputs.table(search, {
columns: ["name"],
header: {name: "Care Service"},
width: 300,
height: 100,
required: false,
value: search, 
multiple: false})
```

### Row {height="70%"}

```{r print}
head(x)
```


## Column {width="80%"}

### Row {height="10%"}

```{ojs}
//| expandable: false

// Transpose data to make it useable in ojs
service = transpose(service_name)

// Create dropdown menu of the names
viewof serviceDropdown = Inputs.select(
  service.map(d => d.name),
  {
    label: "Choose a service",
    unique: true
    }
)
```

### Row {height="70%"}

```{r column_2_row_2}
library(tidyverse)
head(cars)
```

### Row {height="20%"}

```{r column_2_row_3}
library(tidyverse)
head(cars)
```

